module ChampionQuotes
  @@quotes = {
    Aatrox: "Nobody understands me! They called my work a hack job.",
    Thresh: "There is life, there is death, and then there is me.",
    Tryndamere: "My right arm is a lot stronger than my left arm!",
    Gragas: "The only time I have a drinking problem is when I spill it!",
    AurelionSol: "A sun is unimaginable celestial power - and thrilled mortals use theirs to coordinate this 'lunch time'.",
    Cassiopeia: "If you don't control pawns, you are one.",
    Poppy: "Some things are too important to give up on.",
    Ryze: "I got these tattoos in rune prison!",
    Sion: "Blood is the wine of victory.",
    Annie: "I never play with matches.",
    Jhin: "Each bullet is a piece of my soul. Each shot is a piece of me.",
    Nautilus: "When lost in utter darkness, there is nothing left but forward.",
    Karma: "Never become a monster to defeat one.",
    Lux: "There is always lights in the darkness.",
    Ahri: "Let's have some real fun.",
    Olaf: "The worth of a man can be measured by the length of his beard, and the girth of his belt buckle.",
    Viktor: "Adapt or be removed.",
    Singed: "To shake, or not to shake.",
    Garen: "Justice, by law, or by sword.",
    Anivia: "Poor creatures, so confined by a single life.",
    Maokai: "You should not defy nature!",
    Lissandra: "All will kneel... in time.",
    Morgana: "Not all angels are good.",
    Evelynn: "Misery loves company.",
    Fizz:  "The mighty shark stalks his prey.",
    Heimerdinger: "There are three key ingredients to invention: excessive imagination, good old fashioned stick-to-it-iveness, and a rocking good hairstyle!",
    Zed: "Secrets kept are weapons wasted.",
    Rumble: "The bigger they are, the harder I hit 'em.",
    Mordekaiser: "I like my weapons how I like my music... heavy and metal!",
    Sona: "The fanfare ascends.",
    Katarina: "Keep friends close and enemies guessing.",
    KogMaw: "Oblivion come.",
    Ashe: "I always take the high ground.",
    Lulu: "You'll see more with your eyes closed.",
    Karthus: "Pain is the herald of your salvation.",
    Alistar: "Mess with the bull and you get the horns!",
    Darius: "Strength above all.",
    Vayne: "The shadows are to be feared.",
    Udyr: "Feral instinct guides our fist.",
    Varus: "Beware a man with nothing to lose.",
    Jayce: "Strength through progress.",
    Leona: "The sun always rises.",
    Syndra: "People fear what they cannot understand.",
    Pantheon: "I know my path.",
    Khazix: "To truly know someone, eat them and walk a mile in their feet.",
    Riven: "A sword mirrors its owner.",
    Corki: "Bombs away!",
    Caitlyn: "Don't be caught flat footing.",
    Azir: "You need not follow, but you must witness",
    Nidalee: "The untamed know no fear.",
    Kennen: "Big targets are the best! There's more to aim at!",
    Galio: "Justice will be done.",
    Veigar: "Even death trembles in my presence.",
    Brand: "I will blaze a trail.",
    Bard: "*Chimes*",
    Gnar: "Oga manni maxa.",
    Malzahar: "Mortality is weakness.",
    Graves: "Everyone's a hero... till you shoot off a leg or two.",
    Vi: "Why can't I get a straight answer? It's always just 'Oh no! Stop hitting me! Ow, my face!'",
    Kayle: "An eye for an eye.",
    Irelia: "Balance in all things.",
    LeeSin: "Force is meaningless without skill.",
    Illaoi: "It is terrible to be satisfied. The world needs us to chase dreams.",
    Elise: "The truly faithful need not fear the spider's embrace.",
    Volibear: "A fool and his head are easily parted.",
    Nunu: "Speak softly...and ride a big yeti!",
    TwistedFate: "Cheater's just a fancy word for winner.",
    Jax: "Who wants a piece of the champ?!",
    Shyvana: "The might of Demacia will prevail.",
    Kalista: " Nothing is more heinous than treachery.",
    DrMundo: "Mundo will go where he pleases!",
    TahmKench: "A depth of flavor is what I covet.",
    Diana: "The moon will rise. The night will last forever.",
    Bramd: "Is it hot in here or is it just me?",
    Sejuani: "Living in fear is not living at all.",
    Vladimir: "Go ahead, be negative. You'll be just my type.",
    Zac: "Fighting is in my blood... I mean... my goo.",
    RekSai: "*Snarls*",
    Quinn: "A bird's eye view is the best advantage.",
    Akali: "Hesitation is the seed of defeat.",
    Tristana: "War stories don't write themselves.",
    Hecarim: "I am beyond death.",
    Sivir: "Honor is the rust on a dull blade.",
    Lucian: "Everybody dies, some just need a little help.",
    Rengar: "Comfort breeds weakness.",
    Warwick: "It's only fun if they run.",
    Skarner: "My stinger brings ugly death.",
    Malphite: "Let's rock.",
    Yasuo: "The road to ruin is shorter than you think.",
    Xerath: "Flesh and blood; so fragile.",
    Teemo: "Size doesn't mean everything.",
    Renekton: "Light meat, dark meat, it's all the same.",
    Nasus: "No dawn comes without darkness.",
    Draven: "Places to go, me to see.",
    Shaco: "The joke's on you!",
    Swain:  "My destination is absolute.",
    Janna: "Yes, it's true. For only $2.95 a minute, I will leave you breathless.",
    Talon: "The worst part of losing a blade is trying to trace back all my stabbings.",
    Ziggs: "Explosion first, questions later.",
    Ekko: "It's not how much time you have, it's how you use it.",
    Orianna: "Time tick-ticks away.",
    FiddleSticks: "The end is near!",
    Fiora: "Precision and grace.",
    Chogath: "Who will be eaten first?",
    Rammus: "Ok.",
    Leblanc: "t's all smoke and mirrors.",
    Soraka:  "Violence cannot go unanswered.",
    Zilean: "Time flies like an arrow; fruit flies like banana.",
    Nocturne: "People are flames to be blotted out.",
    Jinx: "Let's just behave... said no one, ever.",
    Yorick: "Everything has an expiration date.",
    Urgot: "The fortunate will be eradicated.",
    Kindred: "Embracing life means accepting death.",
    MissFortune: "No prey, no pay.",
    MonkeyKing: "Every mistake is a lesson.",
    Blitzcrank: "Bone is a poor alternative.",
    Shen: "If light travels so fast, how come it's never caught a ninja?",
    Braum: "When life gives you curdled milk, be patient. You get very good cheese!",
    XinZhao: "Find me an immovable object, and I'll put this question to rest!",
    Twitch: "Shooting's easy. Aiming's hard.",
    MasterYi: "Anger gives motivation without purpose.",
    Taric: "I've been to the top of the mountain... and the bottom of the gutter. There's much to learn from both.",
    Amumu: "Come play with me.",
    Gangplank: "The seas and men betray.",
    Trundle: "You can never bash something too many times.",
    Kassadin: "The balance of power must be preserved.",
    Velkoz: "Genders are more easily discerned by the pitch of their cries.",
    Zyra: "Our seasons are reversed: my spring, your fall.",
    Nami: "Sometimes you're the catch. Sometimes you're the bait.",
    JarvanIV: "We shall rest when we are dead!",
    Ezreal: "Know your environment.",
  }

  def self.quotes
    @@quotes
  end
end
